apiVersion: v1
kind: Namespace
metadata:
  name: teamscarlett
  labels:
    name: teamscarlett
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: scarlettquota
  namespace: teamscarlett
spec:
  hard:
    pods: "3"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "3"
    limits.memory: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: teamscarlett
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
