apiVersion: v1
kind: ResourceQuota
metadata:
  name: scarlettquota
  namespace: teamscarlett
spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "3"
    limits.memory: 3Gi