apiVersion: v1
kind: ResourceQuota
metadata:
  name: scarlettquota
  namespace: teamscarlett
spec:
  hard:
    pods: "10"
    requests.cpu: "10"
    requests.memory: 10Gi
    limits.cpu: "20"
    limits.memory: 20Gi